document.write('		<div class="content">	')
document.write('			<h1>Contact Information</h1>	')
document.write('			<ul>	')
document.write('				<li>Office: S-336 &nbsp &nbsp top of the ramp - end of the hallway</li>	')
document.write('				<li>Office Hours: see calendar below, or by appointment</li>	')
document.write('				<li>&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp	')
document.write('					<a href="/johnsontimoj/Common/DOCS/opendoor.pdf">See my open door policy</a></li>	')
document.write('				<li>&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp	')
document.write('					<a href="/johnsontimoj/Common/DOCS/schedule.pdf">Weekly Calendar</a></li>	')
document.write('				<li>&nbsp</li>	')
document.write('				<li>Office Phone: N/A</li>	')
document.write('				<li>Email: <a href="mailto:johnsontimoj@msoe.edu">johnsontimoj@msoe.edu</a></li>	')
document.write('				<li>&nbsp &nbsp &nbsp &nbsp &nbsp For class specific email - prepend all email subjects with	</li>   ')
document.write('				<li> &nbsp &nbsp &nbsp &nbsp &nbsp <em>"class ID"</em>. For example: "<em>ELE 1234</em> - question about quiz 2"</li>	')
document.write('			</ul>	')
document.write('		</div>	')