
document.write('<header class="banner">')
document.write('<!-- Row / Column  for a responsive web page -->')
document.write('<!-- currently not implemented -->')
document.write('<div class = "row">')
document.write('	<div class="col-l">')
document.write('		<!-- MSOE LOGO -->')
document.write('		<a href="https://www.msoe.edu/"><img class="MSOE-Logo" alt="MSOE"  src="/johnsontimoj/Common/IMAGES/Milwaukee-school-of-engineering_logo.png" width="90" /></a>')
				
document.write('		<!-- MSOE NAV -->')
document.write('		<nav class = "MSOE-Nav">')
document.write('			<a href="http://www.msoe.edu/about-msoe">About MSOE</a>  &nbsp &nbsp ') 
document.write('			<a href="https://www.msoe.edu/admissions-aid">Admissions and Aid</a> &nbsp &nbsp')
document.write('			<a href="https://www.msoe.edu/Academics">Academics</a>')
document.write('			<a href="https://www.msoe.edu/campus-experience">Campus Experience</a> &nbsp &nbsp')
document.write('			<a href="http://www.msoe.edu/the-msoe-advantage">The MSOE Advantage</a>') 
document.write('		</nav> ')
document.write('	</div>')
document.write('	<div class="col-r">')
document.write('		<!-- TJ LOGO -->')
document.write('		<div class="tj-logo">')
document.write('			<h1>Dr. Timothy Johnson</h1>')
document.write('		</div>')
document.write('		<!-- TJ NAV -->')
document.write('		<nav class="tj-nav">')
document.write('			<a href="/johnsontimoj/index.html">Dr. Johnson</a> |')
document.write('            <a href="http://www.msoe.edu/academics/engineering-undergraduate-programs/electrical-engineering-overview/">EE Dept</a> |')
 document.write('           <a href="/johnsontimoj/EE2905/index-ee2905.html">EE 2905 |</a>')
 document.write('           <a href="/johnsontimoj/EE3921/index-ee3921.html">EE 3921</a>')
document.write('		</nav>') 
document.write('	</div>')
document.write('</div>')
document.write('</header>')